name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.0"

      - name: Flutter Upgrade
        run: flutter upgrade

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses || true
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Clean
        run: flutter clean

      - name: Build APK
        run: flutter build apk --release

      - name: Debug APK Path
        run: ls -alh build/app/outputs/flutter-apk

      - name: Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
